// This file was generated by mys. DO NOT EDIT!!!

#include "default_and_named_parameters/main.mys.hpp"

namespace mys::default_and_named_parameters::main

{

int foo(int a);

int bar(int a, String& b);

int main(int __argc, const char *__argv[]);

int foo(int a)
{
    return a;
}

int bar(int a, String& b)
{
    return (a + to_int(b));
}

int fie(int a, String& b, int c)
{
    return (a + to_int(b) + c);
}

class Fum : public Object {

public:

    int value;

    Fum(int value)
    {
        this->value = value;
    }

    String __str__() const
    {
        std::stringstream ss;
        ss << "Fum(";
        ss << "value=" << this->value;
        ss << ")";
        return String(ss.str().c_str());
    }

};

int fum(std::shared_ptr<Fum>& a, std::shared_ptr<Fum>& b)
{
    return (a->value + (b ? b->value : throw ValueError("None")));
}

int main(int __argc, const char *__argv[])
{
    (void)__argc;
    (void)__argv;
    std::cout << "foo():        " << " " << foo(1) << std::endl;
    std::cout << "foo(2):       " << " " << foo(2) << std::endl;
    std::cout << "bar(1):       " << " " << [](void) {
        auto a = 1;
        auto b = String("5");

        return (bar(a, b));
    }() << std::endl;
    std::cout << "fie(c=4, a=1):" << " " << [](void) {
        auto a = 1;
        auto b = String("10");
        auto c = 4;

        return (fie(a, b, c));
    }() << std::endl;
    try {
        std::cout << "fum():        " << " " << [](void) {
            auto a = std::make_shared<Fum>(1);
            std::shared_ptr<Fum> b;

            return (fum(a, b));
        }() << std::endl;
    } catch (std::exception& e) {
        std::cout << "Exception: " << e << std::endl;
    }
    std::cout << "fum(b=Fum(2)):" << " " << [](void) {
        auto a = std::make_shared<Fum>(1);
        auto b = std::make_shared<Fum>(2);

        return (fum(a, b));
    }() << std::endl;

    return 0;
}

}

int package_main(int argc, const char *argv[])
{
    return mys::default_and_named_parameters::main::main(argc, argv);
}
