// This file was generated by mys. DO NOT EDIT!!!

#include "mys.hpp"
#include "std/thread.hpp"
#include "message_passing/student.mys.types.hpp"
#include "message_passing/calculator.mys.types.hpp"

namespace message_passing::calculator
{

class Add : public Object {

public:
    float first;
    float second;

    Add(float first, float second);

    virtual ~Add();
};

class Result : public Object {

public:
    float result;

    Result(float result);

    virtual ~Result();
};

class Calculator : public mys::thread::Thread {

public:
    std::optional<std::shared_ptr<message_passing::student::Student>> student;

    Calculator();

    virtual ~Calculator();

    virtual void send_add(std::shared_ptr<Add> message);

    virtual void handle_add(std::shared_ptr<Add> message);

    virtual void handle_stop(std::shared_ptr<mys::thread::Stop> message);
};
    
}
