// This file was generated by mys. DO NOT EDIT!!!

#pragma once

#include "mys.hpp"
#include "std/thread.hpp"
#include "message_passing/calculator.mys.hpp"
#include "message_passing/student.mys.hpp"

namespace message_passing::main
{
}
