// This file was generated by mys. DO NOT EDIT!!!

#pragma once

#include "mys.hpp"

Tuple<int, String> func_1(int a);
int func_2(int a, int b);
int func_3(std::optional<int>& a);
Dict<int, List<float>> func_4(int a);
void func_5();
