// This file was generated by mys. DO NOT EDIT!!!

#include "basics.mys.hpp"

/* mys-embedded-c++-before-namespace start */

#include <before>

/* mys-embedded-c++-before-namespace stop */

namespace mys::basics

{

Tuple<int, String> func_1(std::shared_ptr<int>& a);

int func_2(std::shared_ptr<int>& a, std::shared_ptr<int>& b);

int func_3(std::optional<int>& a);

Dict<int, List<float>> func_4(std::shared_ptr<int>& a);

void func_5(void);

int main(int __argc, const char *__argv[]);

;

/* mys-embedded-c++ start */

#include <not-before>

/* mys-embedded-c++ stop */;

Tuple<int, String> func_1(std::shared_ptr<int>& a)
{
    return Tuple<todo>({(2 * a), "Bar"});
}

int func_2(std::shared_ptr<int>& a, std::shared_ptr<int>& b)
{
    for (auto i: range(b)) {
        a += (i * b);
    }
    return a;
}

int func_3(std::optional<int>& a)
{
    if ((a == None)) {
        return 0;
    } else {
        return (2 * a);
    }
}

Dict<int, List<float>> func_4(std::shared_ptr<int>& a)
{
    return MakeDict<todo>({});
}

void func_5(void)
{
    try {
        throw Exception();
    } catch (std::exception& e) {
        std::cout << "func_5():      An exception occurred." << std::endl;
    }
}

class Calc : public Object {

public:

    int value;

    void triple(void)
    {
        this->value *= 3;
    }

    Calc(int value)
    {
        this->value = value;
    }

    virtual String __str__() const
    {
        std::stringstream ss;
        ss << "Calc(";
        ss << "value=" << this->value;
        ss << ")";
        return String(ss.str().c_str());
    }

};

int main(int __argc, const char *__argv[])
{
    auto argv = create_args(__argc, __argv);
    value = int(argv[1]);
    std::cout << "func_1(value):" << " " << func_1(value) << std::endl;
    std::cout << "func_2(value):" << " " << func_2(value) << std::endl;
    std::cout << "func_3(None): " << " " << func_3(None) << std::endl;
    std::cout << "func_3(value):" << " " << func_3(value) << std::endl;
    std::cout << "func_4(value):" << " " << func_4(value) << std::endl;
    func_5();
    calc = Calc(value);
    calc.triple();
    std::cout << "calc:         " << " " << calc << std::endl;

    return 0;
}

}



int package_main(int argc, const char *argv[])
{
    return mys::basics::main(argc, argv);
}
