// This file was generated by mys. DO NOT EDIT!!!

#pragma once

#include "mys.hpp"
#include "mypkg1/lib.mys.hpp"
#include "mypkg2/mod1.mys.hpp"
#include "mypkg2/subpkg1/mod1.mys.hpp"
#include "mypkg3/subpkg1/mod1.mys.hpp"
#include "mypkg4/lib.mys.hpp"
